package com.xusong.model;

import com.xusong.model.base.BaseGirl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Girl extends BaseGirl<Girl> {
	public static final Girl dao = new Girl().dao();
}
